### ISSUE TITLE
Procedure probably called with too many arguments (4 bytes in excess)

### ISSUE THREAD

**Issue by EliCDavis** [bayangan1991/PYXInput#11]
Upon successful installation, I run the recommended test:

```python
import pyxinput

pyxinput.test_virtual()
```

And receive the output:

```pythyon
Testings multiple connections
Connecting Controller:
Traceback (most recent call last):
  File ".\agh.py", line 3, in <module>
    pyxinput.test_virtual()
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 142,
in main
    cons.append(vController())
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 45, in __init__
    self.PlugIn()
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 60, in PlugIn
    ids = self.available_ids()
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 54, in available_ids
    1, 5) if _xinput.isControllerExists(c_int(x)) == 0]
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 54, in <listcomp>
    1, 5) if _xinput.isControllerExists(c_int(x)) == 0]
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
Exception ignored in: <bound method vController.__del__ of <pyxinput.virtual_controller.vController object at 0x02F46350>>
Traceback (most recent call last):
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 49, in __del__
    self.UnPlug()
  File "C:\Users\Eli Davis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyxinput\virtual_controller.py", line 75, in UnPlug
    _xinput.UnPlug(c_uint(self.id))
ValueError: Procedure probably called with too many arguments (4 bytes in excess)
```

Windows 10, Python version 3.6.5

**Comment by EliCDavis** [comment]
I've tested this in Python 3.6.1 with success oddly enough.

**Comment by LordCommanderMay** [comment]
Ik this was 7 months ago but I got the same error when I was using 32-bit python. using 64-bit python solved the issue.
